export const DEFAULT_PAGI_PARAMS = {
  size: 100,
  page: 0,
};

export enum ROLE_CODE {
  DEPARTMENT_DIRECTOR = 'DEPARTMENT_DIRECTOR',
  TEAM_DIRECTOR = 'TEAM_DIRECTOR',
  ARCHIVIST = 'ARCHIVIST',
  ADMIN = 'ADMIN',
  SPECIALIST = 'SPECIALIST',
}
